require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

def all_pods  
  config = use_native_modules!
  
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'ReactNativeNavigation', :path => '../../'
  pod 'HMSegmentedControl'
end

target 'playground' do
  all_pods
end

target 'NavigationTests' do
  all_pods
  pod 'OCMock'
end

target 'NavigationIOS12Tests' do
  all_pods
  pod 'OCMock'
end

target 'SnapshotTests' do
  all_pods
  pod 'OCMock'
end